name: Generate Quantic Docs
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  get-quantic-discussions:
    runs-on: ubuntu-latest
    run: |
      last_discussion_date=$(curl -s https://github.com/npushkarskii/discussions-sandbox/discussions/categories/announcements | grep -m 1 -o '<relative-time datetime=\".*\" ' | sed -e 's/.*"\(.*\)\T\(.*\)/\1/')
      current_date=$(date -I)
      diff <(echo "$last_discussion_date") <(echo "$current_date") > /dev/null
      date_comparison=$(echo $?)
    if: $(echo $date_comparison) == 0  
    steps:
      - uses: actions/checkout@v2 
      - name: Make a new Branch on the docs site
        uses: peterjgrainger/action-create-branch@b48b0ca0e307c9b56f059b70274984ffeaa90a43
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "Coveo Quantic Release" 
      - name: Create a PR for new Quantic docs
        uses: gr2m/create-or-update-pull-request-action@cbfed2a38aedceab8d9fc0d9ac14890fc181d39e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Generate Quantic Docs"
          branch: "coveo-quantic"
          commit-message: "generate docs via a --full-build"
          author: "DocsBot<beep-boop-beep@users.noreply.github.com>"
          assignees: npushkarskii
