name: Generate Quantic Docs
on: workflow_dispatch
#   schedule:
#     - cron:  '*/5 * * * *'
jobs:
  get-quantic-discussions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Quantic discussions and compare dates
        id: compare_dates
        run: |
          set -o pipefail
          last_discussion_date=$(curl -s https://github.com/npushkarskii/discussions-sandbox/discussions/categories/announcements | grep -m 1 -o '<relative-time datetime=\".*\" ' | sed -e 's/.*"\(.*\)\T\(.*\)/\1/')
          current_date=$(date -I)
          date_comparison=$(diff <(echo "$last_discussion_date") <(echo "$current_date"); echo $?)
          echo "::set-output name=comparison::$(($date_comparison))"
      - name: Make a new Branch on the docs site
        if: ${{ steps.compare_dates.outputs.comparison == 0}} 
        uses: peterjgrainger/action-create-branch@b48b0ca0e307c9b56f059b70274984ffeaa90a43
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "coveo-quantic-release"
      - name: Adds stub changes so that a PR can be created
        run: |
          echo "This file is just a trick so that GH can create a PR" > remove_this_file    
      - name: Create a PR for new Quantic docs
        uses: gr2m/create-or-update-pull-request-action@cbfed2a38aedceab8d9fc0d9ac14890fc181d39e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Generate Quantic Docs"
          branch: "coveo-quantic-release"
          commit-message: "generate docs via a --full-build"
          author: "DocsBot<beep-boop-beep@users.noreply.github.com>"
          assignees: npushkarskii
